# Question bank build script (ASCII-only source to avoid PS5.1 encoding issues)
# - Merge src/data/questions/{prefix}_*.json partials -> {prefix}.json (renumber ids)
# - Concatenate all {prefix}.json (final files) -> src/data/bank.js (window.QUESTION_BANK)
param(
  [string]$Root = (Split-Path -Parent $MyInvocation.MyCommand.Path)
)
$ErrorActionPreference = "Stop"
$qDir = Join-Path $Root "src\data\questions"

function Read-Json($path) {
  $raw = Get-Content -Raw -Encoding UTF8 $path
  return ,($raw | ConvertFrom-Json)
}

# 1) Merge partials: files like goryeo_A.json, goryeo_B.json -> goryeo.json
$partGroups = Get-ChildItem $qDir -Filter "*_*.json" -ErrorAction SilentlyContinue |
  Group-Object { ($_.BaseName -split "_")[0] }

foreach ($g in $partGroups) {
  $prefix = $g.Name
  $all = @()
  foreach ($f in ($g.Group | Sort-Object Name)) {
    $items = Read-Json $f.FullName
    if ($items) { $all += $items }
  }
  $i = 0
  foreach ($q in $all) {
    $i++
    $q.id = ("{0}-{1:000}" -f $prefix, $i)
  }
  $outPath = Join-Path $qDir "$prefix.json"
  ($all | ConvertTo-Json -Depth 10) | Out-File -Encoding UTF8 $outPath
  Write-Host ("[merge] {0}: {1} items -> {2}" -f $prefix, $all.Count, (Split-Path -Leaf $outPath))
}

# 2) Build bank.js from final files only (basename without underscore)
$bank = @()
$finalFiles = Get-ChildItem $qDir -Filter "*.json" | Where-Object { $_.BaseName -notmatch "_" }
foreach ($f in $finalFiles) {
  $items = Read-Json $f.FullName
  if ($items) { $bank += $items }
}
$json = $bank | ConvertTo-Json -Depth 10
$bankJs = "// AUTO-GENERATED by build.ps1 - do not edit.`r`nwindow.QUESTION_BANK = $json;`r`n"
$bankPath = Join-Path $Root "src\data\bank.js"
$bankJs | Out-File -Encoding UTF8 $bankPath
Write-Host ("[bank] total {0} items -> src/data/bank.js" -f $bank.Count)
